language: node_js
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
packages:
  - gcc-4.8
  - g++-4.8
  - clang
node_js:
  - "10.19"
services:
  - redis-server
before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"
after_script:
  - npm run test
